[tool.poetry]
name = "scru64"
version = "0.3.1"
description = "SCRU64: Sortable, Clock-based, Realm-specifically Unique identifier"
authors = ["LiosK <contact@mail.liosk.net>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/scru64/python"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
